<a href="https://colab.research.google.com/github/Saxon-account/Saxon-account/blob/main/Saxon_python_ai_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We will learn:
* Numpy
* matplotlib
* pandas

# Numpy
What is Numpy? And what is it used for? How is it different from using a python list?

Numpy array
- fixed array
- same datatype
- static array
- more efficient

Import Numpy package

In [ ]:
import numpy as np

## Arrays


In [ ]:
# Create a numpy array of rank 1 from a python list [1, 2, 3]
pl = [1, 2, 3]
a = np.array(pl)
print(pl)
print(a)

[1, 2, 3]
[1 2 3]


In [ ]:
# Print type
print(type(pl))
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(3,)


In [ ]:
# Create a rank 2 array with dimensions 2 rows and 3 columns

x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Create an identity matrix of size 3

id = np.eye(3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Create and print a 3D numpy array [[[1,2,3],[4,5,6]][[7,8,9],[10,11,12]]]
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Create an array of all 0's w dimensions (2, 3, 2)
c = np.array([[[0,0],[0,0],[0,0]],[[0,0],[0,0],[0,0]]])
print(c)
print(c.shape)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]
(2, 3, 2)


In [ ]:
# Create a random array
rand = np.random.random((2, 3))
print(rand)

[[0.6776057  0.79364021 0.50512753]
 [0.59572773 0.90361312 0.08593851]]


#Array Indexing

In [ ]:
# Create 2D array [1,2,3], [4,5,6]
# Access and print 2

x = np.array([[1, 2, 3],[4, 5, 6]])
print(twoD[0,1])

2


In [ ]:
# Shape
print(x.shape)

(2, 3)


In [ ]:
# Access a sub matrix [2, 3, 5, 6]
print(x[:, 1: ])


[[2 3]
 [5 6]]


In [ ]:
# Reshape [1 2 3 4 5 6]
print(x.reshape(6))

print(x.reshape(3,2))

print(x.reshape(2,3))

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Slicing
y= x[:, 1: ]
print(y, y.shape)

[[2 3]
 [5 6]] (2, 2)


In [ ]:
y[0,0] = 10
print(y)
print(x)

[[10  3]
 [ 5  6]]
[[ 1 10  3]
 [ 4  5  6]]


In [ ]:
# Try slicing with python list and updating
# Assign slice to another variable and update new variable
list = [1,2,3,4,5,6]
y = list[:]

In [ ]:
a = np.array([1, 2, 3, 4, 5])
# 3 and 5
a[2], a[4]
# or
indices = [2, 4]
a[indices]

array([3, 5])

In [ ]:
# 2D array
x = np.array([[1,2,3],[4,5,6]])

# Print 2 and 6 and 3
# 2 -> [0, 1]
# 6 -> [1, 2]
# 3 -> [0, 2]

row_indices = [0, 1, 0]
col_indices = [1, 2, 2]
x[row_indices, col_indices]

array([2, 6, 3])

In [ ]:
# Data type of array elements
type(x[1, 2])

print(x.dtype)

int64


#Boolean array indexing

In [ ]:
x = np.array([[1,2,3],[4,5,6]])

bool_indices = (x % 2 ==0)
print(bool_indices)

[[False  True False]
 [ True False  True]]


In [ ]:
x[bool_indices]

array([2, 4, 6])

In [ ]:
x[x%2==0]

array([2, 4, 6])

## Data type

In [ ]:
x = np.array([1.0, 2.5], dtype = np.int64)
x.dtype

dtype('int64')

In [ ]:
print(x)

[1 2]


## Array Math

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype = np.float64)
y = np.array([[5, 6], [7, 8]], dtype = np.float64)

print(x)
print(y)



[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [ ]:
# Elementwise
# add
x + y
# subtract
x - y
# multiply
x * y
# divide
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
# Elementwise functions
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [ ]:
# Dot product
v = np.array([1, 2])
w = np.array([3, 4])

print(np.dot(v, w))
print(v.dot(w))
print(v @ w)

11
11
11


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print(x)
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [ ]:
# Max, row max
# Min, row min
print(x.max())
print(x.min())

1

## Broadcasting

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

(4, 3)

In [ ]:
x.shape

In [ ]:
v.shape

In [ ]:
print(x)
print(x+v) #Makes copies of v to fit dimensions of x

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Use matplotlib library to plot a sine function

In [ ]:
import matplotlib as mpl